apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vllm-test 
  janus-idp.io/tekton: vllm-test
  backstage.io/kubernetes-id: vllm-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vllm-test
resources: 
- application-dev.yaml